day07-1 : day07-1.o
	gcc -o day07-1 day07-1.c

day07-1.o : day07-1.c
	gcc -c day07-1.c

run1 : day07-1
	./day07-1

day07-2 : day07-2.o
	gcc -o day07-2 day07-2.c

day07-2.o : day07-2.c
	gcc -c day07-2.c

run2 : day07-2
	./day07-2

clean :
	rm -f day07-1 day07-2 *.o