day08-1 : day08-1.o
	gcc -o day08-1 day08-1.c

day08-1.o : day08-1.c
	gcc -c day08-1.c

run1 : day08-1
	./day08-1

day08-2 : day08-2.o
	gcc -o day08-2 day08-2.c

day08-2.o : day08-2.c
	gcc -c day08-2.c

run2 : day08-2
	./day08-2

clean :
	rm -f day08-1 day08-2 *.o