day02-1 : day02-1.o
	gcc -o day02-1 day02-1.o

day02-1.o : day02-1.c
	gcc -c day02-1.c

day02-2 : day02-2.o
	gcc -o day02-2 day02-2.o

day02-2.o : day02-2.c
	gcc -c day02-2.c

run1 : day02-1
	./day02-1

run2 : day02-2
	./day02-2

clean :
	rm -f day02-1 day02-2 *.o