day04-1 : day04-1.o
	gcc -o day04-1 day04-1.c

day04-1.o : day04-1.c
	gcc -c day04-1.c

run1 : day04-1
	./day04-1

day04-2 : day04-2.o
	gcc -o day04-2 day04-2.c

day04-2.o : day04-2.c
	gcc -c day04-2.c

run2 : day04-2
	./day04-2

clean :
	rm -f day04-1 day04-2 *.o