day05-1 : day05-1.o
	gcc -o day05-1 day05-1.c

day05-1.o : day05-1.c
	gcc -c day05-1.c

run1 : day05-1
	./day05-1

day05-2 : day05-2.o
	gcc -o day05-2 day05-2.c

day05-2.o : day05-2.c
	gcc -c day05-2.c

run2 : day05-2
	./day05-2

clean :
	rm -f day05-1 day05-2 *.o